version: '3.4'
services:
  db:
    image: postgres:latest
    container_name: 'postgres-bookstore'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    restart: always

    networks:
      - bookstore-network

  api:
    image: mathaews/bookstore
    restart: always

    build:
      context: ./
      dockerfile: Dockerfile

    working_dir: /bookstore

    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_EVIROMENT: Production

    ports:
      - "8080:8080"

    volumes:
      - .:/bookstore
      - ~/.m2:/root/.m2

    command: mvn clean spring-boot:run

    links:
      - db
    depends_on:
      - db
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge
