name: Bookstore Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d
      
    env:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 1234
      TIMEZONE: America/Sao_Paulo
      HOST_DB: db
